version: '3'

services:
  app:
    container_name: go_app
    build: .
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - ${ROOT_PROJECT}:/go/src/app/
    depends_on:
      - postgresql
    networks:
      - fullstack

  postgresql:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - fullstack

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgresql
    ports:
      - "5050:80"
    networks:
      - fullstack
    restart: on-failure

volumes:
  app:
  postgresql:

networks:
  fullstack:
    driver: bridge
